SET search_path TO metaserver, public;

CREATE OR REPLACE FUNCTION metaserver.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

ALTER TABLE metaserver.users
    ADD COLUMN IF NOT EXISTS user_no bigint GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS login_id varchar(100),
    ADD COLUMN IF NOT EXISTS password_hash text,
    ADD COLUMN IF NOT EXISTS user_name varchar(100),
    ADD COLUMN IF NOT EXISTS user_type varchar(30) NOT NULL DEFAULT 'member',
    ADD COLUMN IF NOT EXISTS auth_provider varchar(30) NOT NULL DEFAULT 'firebase',
    ADD COLUMN IF NOT EXISTS mfa_enabled boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS locked_at timestamptz,
    ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS created_by uuid,
    ADD COLUMN IF NOT EXISTS updated_by uuid,
    ADD COLUMN IF NOT EXISTS deleted_by uuid;

UPDATE metaserver.users
SET
    user_name = COALESCE(user_name, display_name, email, firebase_uid),
    login_id = COALESCE(login_id, email),
    auth_provider = COALESCE(auth_provider, 'firebase'),
    user_type = COALESCE(user_type, 'member'),
    is_active = COALESCE(is_active, status = 'active')
WHERE user_name IS NULL
   OR login_id IS NULL
   OR auth_provider IS NULL
   OR user_type IS NULL;

ALTER TABLE metaserver.users
    ALTER COLUMN user_name SET DEFAULT '',
    ALTER COLUMN user_name SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_user_no
    ON metaserver.users (user_no);

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_login_id_not_deleted
    ON metaserver.users (lower(login_id))
    WHERE login_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS ix_users_type_active
    ON metaserver.users (user_type, is_active);

CREATE INDEX IF NOT EXISTS ix_users_provider
    ON metaserver.users (auth_provider);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_users_created_by'
          AND conrelid = 'metaserver.users'::regclass
    ) THEN
        ALTER TABLE metaserver.users
            ADD CONSTRAINT fk_users_created_by
            FOREIGN KEY (created_by) REFERENCES metaserver.users(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_users_updated_by'
          AND conrelid = 'metaserver.users'::regclass
    ) THEN
        ALTER TABLE metaserver.users
            ADD CONSTRAINT fk_users_updated_by
            FOREIGN KEY (updated_by) REFERENCES metaserver.users(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_users_deleted_by'
          AND conrelid = 'metaserver.users'::regclass
    ) THEN
        ALTER TABLE metaserver.users
            ADD CONSTRAINT fk_users_deleted_by
            FOREIGN KEY (deleted_by) REFERENCES metaserver.users(id);
    END IF;
END $$;

DROP TRIGGER IF EXISTS trg_users_updated_at ON metaserver.users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON metaserver.users
FOR EACH ROW
EXECUTE PROCEDURE metaserver.touch_updated_at();

COMMENT ON COLUMN metaserver.users.user_no IS '관리자 화면과 운영 로그에서 보기 쉬운 순번형 사용자 번호.';
COMMENT ON COLUMN metaserver.users.login_id IS '이메일/로컬 로그인/관리자 검색용 로그인 ID. Firebase UID와 별개이다.';
COMMENT ON COLUMN metaserver.users.password_hash IS 'LOCAL 인증을 추가할 때 사용하는 비밀번호 해시. Firebase-only 사용자는 NULL이다.';
COMMENT ON COLUMN metaserver.users.user_name IS '운영 화면과 프로필에서 쓰는 사용자 이름.';
COMMENT ON COLUMN metaserver.users.user_type IS 'member, admin, operator, system 등 사용자 유형.';
COMMENT ON COLUMN metaserver.users.auth_provider IS '대표 인증 제공자. firebase, local, google, apple, facebook 등.';
COMMENT ON COLUMN metaserver.users.mfa_enabled IS 'MFA 사용 여부.';
COMMENT ON COLUMN metaserver.users.locked_at IS '계정 잠금 시각.';
COMMENT ON COLUMN metaserver.users.is_active IS '운영 화면 필터용 활성 여부. status와 함께 관리한다.';
COMMENT ON COLUMN metaserver.users.created_by IS '사용자를 생성한 내부 사용자 ID.';
COMMENT ON COLUMN metaserver.users.updated_by IS '마지막으로 사용자를 수정한 내부 사용자 ID.';
COMMENT ON COLUMN metaserver.users.deleted_by IS '사용자를 삭제 처리한 내부 사용자 ID.';
