CREATE SCHEMA IF NOT EXISTS metaserver;
SET search_path TO metaserver, public;

CREATE OR REPLACE FUNCTION ms_generate_uuid()
RETURNS uuid
LANGUAGE sql
VOLATILE
AS $$
    SELECT md5(random()::text || clock_timestamp()::text || txid_current()::text)::uuid;
$$;

CREATE OR REPLACE FUNCTION touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TYPE user_status AS ENUM ('active', 'suspended', 'deleted');
CREATE TYPE broker_code AS ENUM ('kis');
CREATE TYPE broker_environment AS ENUM ('paper', 'live');
CREATE TYPE broker_connection_status AS ENUM ('pending', 'active', 'revoked', 'error');
CREATE TYPE account_status AS ENUM ('active', 'disabled', 'revoked');
CREATE TYPE instrument_type AS ENUM ('stock', 'etf', 'etn', 'reit', 'index', 'other');
CREATE TYPE asset_class AS ENUM ('domestic_stock', 'overseas_stock', 'crypto');
CREATE TYPE order_side AS ENUM ('buy', 'sell');
CREATE TYPE order_kind AS ENUM ('market', 'limit', 'after_hours', 'reservation', 'other');
CREATE TYPE order_status AS ENUM (
    'draft',
    'received',
    'submitted',
    'accepted',
    'partially_filled',
    'filled',
    'amend_requested',
    'cancel_requested',
    'canceled',
    'rejected',
    'expired',
    'failed'
);
CREATE TYPE order_source AS ENUM ('mobile', 'web', 'admin', 'system');
CREATE TYPE alert_status AS ENUM ('active', 'triggered', 'paused', 'deleted');

CREATE TABLE users (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    user_no bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    firebase_uid text NOT NULL UNIQUE,
    login_id varchar(100),
    password_hash text,
    email text,
    email_verified boolean NOT NULL DEFAULT false,
    display_name text,
    user_name varchar(100) NOT NULL DEFAULT '',
    photo_url text,
    user_type varchar(30) NOT NULL DEFAULT 'member',
    auth_provider varchar(30) NOT NULL DEFAULT 'firebase',
    mfa_enabled boolean NOT NULL DEFAULT false,
    locked_at timestamptz,
    is_active boolean NOT NULL DEFAULT true,
    status user_status NOT NULL DEFAULT 'active',
    last_login_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid REFERENCES users(id),
    updated_by uuid REFERENCES users(id),
    deleted_by uuid REFERENCES users(id)
);

CREATE UNIQUE INDEX ux_users_email_not_deleted
    ON users (lower(email))
    WHERE email IS NOT NULL AND deleted_at IS NULL;

CREATE UNIQUE INDEX ux_users_login_id_not_deleted
    ON users (lower(login_id))
    WHERE login_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX ix_users_type_active ON users(user_type, is_active);
CREATE INDEX ix_users_provider ON users(auth_provider);

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE PROCEDURE touch_updated_at();

CREATE TABLE user_profiles (
    user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    real_name_encrypted text,
    phone_encrypted text,
    phone_hash text,
    birth_date date,
    locale text NOT NULL DEFAULT 'ko-KR',
    timezone text NOT NULL DEFAULT 'Asia/Seoul',
    marketing_opt_in boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE auth_identities (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider text NOT NULL,
    provider_uid text NOT NULL,
    email text,
    email_verified boolean NOT NULL DEFAULT false,
    raw_claims jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider, provider_uid)
);

CREATE INDEX ix_auth_identities_user_id ON auth_identities(user_id);

CREATE TABLE roles (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    code text NOT NULL UNIQUE,
    name text NOT NULL,
    description text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_roles (
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    granted_by uuid REFERENCES users(id),
    granted_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE user_devices (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    platform text NOT NULL,
    device_id_hash text,
    push_token text,
    app_version text,
    last_seen_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    revoked_at timestamptz
);

CREATE INDEX ix_user_devices_user_id ON user_devices(user_id);

CREATE TABLE terms_versions (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    code text NOT NULL,
    title text NOT NULL,
    version text NOT NULL,
    body_url text,
    required boolean NOT NULL DEFAULT true,
    effective_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (code, version)
);

CREATE TABLE user_terms_agreements (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    terms_version_id uuid NOT NULL REFERENCES terms_versions(id),
    agreed boolean NOT NULL,
    ip_address inet,
    user_agent text,
    agreed_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, terms_version_id)
);

CREATE TABLE login_events (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    user_id uuid REFERENCES users(id) ON DELETE SET NULL,
    firebase_uid text,
    provider text,
    success boolean NOT NULL,
    failure_reason text,
    ip_address inet,
    user_agent text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_login_events_user_created ON login_events(user_id, created_at DESC);

CREATE TABLE broker_connections (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    broker broker_code NOT NULL DEFAULT 'kis',
    environment broker_environment NOT NULL DEFAULT 'paper',
    status broker_connection_status NOT NULL DEFAULT 'pending',
    external_user_ref text,
    encrypted_payload text,
    token_expires_at timestamptz,
    last_synced_at timestamptz,
    error_code text,
    error_message text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    revoked_at timestamptz
);

CREATE INDEX ix_broker_connections_user_id ON broker_connections(user_id);
CREATE UNIQUE INDEX ux_broker_connections_user_env_active
    ON broker_connections(user_id, broker, environment)
    WHERE status IN ('pending', 'active');

CREATE TABLE trading_accounts (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    broker_connection_id uuid NOT NULL REFERENCES broker_connections(id) ON DELETE CASCADE,
    broker broker_code NOT NULL DEFAULT 'kis',
    environment broker_environment NOT NULL DEFAULT 'paper',
    account_no_masked text NOT NULL,
    account_no_hash text NOT NULL,
    encrypted_account_ref text,
    account_alias text,
    product_code text,
    currency text NOT NULL DEFAULT 'KRW',
    status account_status NOT NULL DEFAULT 'active',
    is_primary boolean NOT NULL DEFAULT false,
    last_synced_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (broker, environment, account_no_hash)
);

CREATE INDEX ix_trading_accounts_user_id ON trading_accounts(user_id);
CREATE INDEX ix_trading_accounts_connection_id ON trading_accounts(broker_connection_id);

CREATE TABLE instruments (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    asset_class asset_class NOT NULL DEFAULT 'domestic_stock',
    asset_code text,
    market text NOT NULL,
    market_code text,
    symbol text NOT NULL,
    isin text,
    name_ko text NOT NULL,
    name_en text,
    instrument_type instrument_type NOT NULL DEFAULT 'stock',
    currency text NOT NULL DEFAULT 'KRW',
    quote_currency text,
    base_currency text,
    exchange_name text,
    is_tradable boolean NOT NULL DEFAULT true,
    lot_size numeric(20, 6) NOT NULL DEFAULT 1,
    tick_size numeric(20, 6),
    price_scale numeric(20, 8) NOT NULL DEFAULT 1,
    listed_at date,
    delisted_at date,
    raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (market, symbol)
);

CREATE INDEX ix_instruments_symbol ON instruments(symbol);
CREATE INDEX ix_instruments_name_ko ON instruments(name_ko);
CREATE UNIQUE INDEX ux_instruments_asset_code
    ON instruments(asset_code)
    WHERE asset_code IS NOT NULL;
CREATE INDEX ix_instruments_asset_class_market
    ON instruments(asset_class, market, symbol);

CREATE TABLE watchlists (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name text NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    is_default boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_watchlists_user_id ON watchlists(user_id);

CREATE TABLE watchlist_items (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    watchlist_id uuid NOT NULL REFERENCES watchlists(id) ON DELETE CASCADE,
    instrument_id uuid NOT NULL REFERENCES instruments(id) ON DELETE CASCADE,
    sort_order integer NOT NULL DEFAULT 0,
    memo text,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (watchlist_id, instrument_id)
);

CREATE INDEX ix_watchlist_items_instrument_id ON watchlist_items(instrument_id);

CREATE TABLE trade_orders (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    trading_account_id uuid NOT NULL REFERENCES trading_accounts(id) ON DELETE RESTRICT,
    instrument_id uuid NOT NULL REFERENCES instruments(id) ON DELETE RESTRICT,
    source order_source NOT NULL,
    client_order_id text NOT NULL,
    broker broker_code NOT NULL DEFAULT 'kis',
    environment broker_environment NOT NULL DEFAULT 'paper',
    kis_order_no text,
    kis_original_order_no text,
    side order_side NOT NULL,
    order_kind order_kind NOT NULL,
    quantity numeric(20, 6) NOT NULL CHECK (quantity > 0),
    limit_price numeric(20, 6),
    currency text NOT NULL DEFAULT 'KRW',
    status order_status NOT NULL DEFAULT 'received',
    submitted_at timestamptz,
    accepted_at timestamptz,
    completed_at timestamptz,
    rejected_at timestamptz,
    rejection_reason text,
    broker_status_code text,
    broker_message text,
    request_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    response_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, client_order_id)
);

CREATE INDEX ix_trade_orders_user_created ON trade_orders(user_id, created_at DESC);
CREATE INDEX ix_trade_orders_account_created ON trade_orders(trading_account_id, created_at DESC);
CREATE INDEX ix_trade_orders_instrument_created ON trade_orders(instrument_id, created_at DESC);
CREATE INDEX ix_trade_orders_kis_order_no ON trade_orders(kis_order_no);

CREATE TABLE order_events (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    order_id uuid NOT NULL REFERENCES trade_orders(id) ON DELETE CASCADE,
    previous_status order_status,
    next_status order_status NOT NULL,
    event_type text NOT NULL,
    message text,
    broker_status_code text,
    broker_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_by uuid REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_order_events_order_created ON order_events(order_id, created_at);

CREATE TABLE executions (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    order_id uuid NOT NULL REFERENCES trade_orders(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    trading_account_id uuid NOT NULL REFERENCES trading_accounts(id) ON DELETE RESTRICT,
    instrument_id uuid NOT NULL REFERENCES instruments(id) ON DELETE RESTRICT,
    broker broker_code NOT NULL DEFAULT 'kis',
    environment broker_environment NOT NULL DEFAULT 'paper',
    broker_execution_id text,
    execution_no text,
    executed_quantity numeric(20, 6) NOT NULL CHECK (executed_quantity > 0),
    executed_price numeric(20, 6) NOT NULL CHECK (executed_price >= 0),
    executed_amount numeric(24, 6) NOT NULL CHECK (executed_amount >= 0),
    commission_amount numeric(20, 6) NOT NULL DEFAULT 0,
    tax_amount numeric(20, 6) NOT NULL DEFAULT 0,
    currency text NOT NULL DEFAULT 'KRW',
    executed_at timestamptz NOT NULL,
    raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_executions_order_id ON executions(order_id);
CREATE INDEX ix_executions_user_executed ON executions(user_id, executed_at DESC);
CREATE INDEX ix_executions_account_executed ON executions(trading_account_id, executed_at DESC);

CREATE TABLE account_balance_snapshots (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    trading_account_id uuid NOT NULL REFERENCES trading_accounts(id) ON DELETE CASCADE,
    cash_balance numeric(24, 6) NOT NULL DEFAULT 0,
    available_cash numeric(24, 6) NOT NULL DEFAULT 0,
    total_asset_value numeric(24, 6),
    total_purchase_amount numeric(24, 6),
    total_eval_amount numeric(24, 6),
    total_profit_loss numeric(24, 6),
    currency text NOT NULL DEFAULT 'KRW',
    raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    snapshot_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_balance_snapshots_account_time
    ON account_balance_snapshots(trading_account_id, snapshot_at DESC);

CREATE TABLE position_snapshots (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    trading_account_id uuid NOT NULL REFERENCES trading_accounts(id) ON DELETE CASCADE,
    instrument_id uuid NOT NULL REFERENCES instruments(id) ON DELETE RESTRICT,
    quantity numeric(20, 6) NOT NULL DEFAULT 0,
    available_quantity numeric(20, 6) NOT NULL DEFAULT 0,
    average_price numeric(20, 6),
    current_price numeric(20, 6),
    purchase_amount numeric(24, 6),
    evaluation_amount numeric(24, 6),
    profit_loss numeric(24, 6),
    profit_loss_rate numeric(12, 6),
    currency text NOT NULL DEFAULT 'KRW',
    raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    snapshot_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_position_snapshots_account_time
    ON position_snapshots(trading_account_id, snapshot_at DESC);
CREATE INDEX ix_position_snapshots_instrument
    ON position_snapshots(instrument_id, snapshot_at DESC);

CREATE TABLE price_alerts (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    instrument_id uuid NOT NULL REFERENCES instruments(id) ON DELETE CASCADE,
    condition_type text NOT NULL,
    target_price numeric(20, 6) NOT NULL,
    status alert_status NOT NULL DEFAULT 'active',
    triggered_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_price_alerts_active
    ON price_alerts(instrument_id, status)
    WHERE status = 'active';

CREATE TABLE audit_events (
    id uuid PRIMARY KEY DEFAULT ms_generate_uuid(),
    user_id uuid REFERENCES users(id) ON DELETE SET NULL,
    actor_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
    event_type text NOT NULL,
    entity_type text,
    entity_id uuid,
    ip_address inet,
    user_agent text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_audit_events_user_created ON audit_events(user_id, created_at DESC);
CREATE INDEX ix_audit_events_entity ON audit_events(entity_type, entity_id);

INSERT INTO roles (code, name, description)
VALUES
    ('member', 'Member', 'Default MetaServer member'),
    ('admin', 'Admin', 'MetaServer administrator'),
    ('operator', 'Operator', 'Customer support and operations')
ON CONFLICT (code) DO NOTHING;
